In [11]:
import numpy as np

In [35]:
x=np.arange(12).reshape(4,3)

In [36]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
y=np.arange(10,22).reshape(3,4)

In [38]:
z=x+y

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [28]:
z

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [29]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
y

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [31]:
t=x-y

In [32]:
t


array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [33]:
np.sin(x)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [34]:
np.log(x)

C:\Users\slymn\AppData\Local\Temp/ipykernel_14704/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])