In [2]:
import numpy as np

In [5]:
x=np.arange(25).reshape(5,5)

In [6]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
x[2][2]

12

In [8]:
y=np.arange(1,20)

In [13]:
z=y % 5

In [10]:
y[y>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
z

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
      dtype=int32)