In [1]:
import numpy as np

In [35]:
x=[1,2,3,4,5]

In [36]:
y=[[1,2,3],[4,5,6],[7,8,9]]

In [63]:
z=np.array(y)

In [64]:
np.zeros((3,3)) - 5

array([[-5., -5., -5.],
       [-5., -5., -5.],
       [-5., -5., -5.]])

In [65]:
x=np.array(x)

In [66]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [70]:
x.max()

5

In [71]:
x.min()

1

In [72]:
np.random.randn(5)

array([-0.42421886, -0.06778216, -1.75034554,  0.70170364,  1.38963506])

In [73]:
np.random.randint(1,100)

70

In [74]:
x.argmax()

4

In [75]:
x.argmin()

0

In [78]:
z.argmin()

0

In [79]:
z.argmax()

8